/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package src;
import src.controller.*;

public class App {
     

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        GameController controlleur = new GameController();
        controlleur.start();
        System.out.println(new App().getGreeting());
    }
}
